spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:${WEATHER_APP_DB_NAME}
    generate-unique-name: false
    name: ${WEATHER_APP_DB_NAME}
    username: ${WEATHER_APP_DB_USERNAME}
    password: ${WEATHER_APP_DB_PASSWORD}
    hikari:
      connection-timeout: 20_000 # 20 секунд
      minimum-idle: 4
      maximum-pool-size: 8
      max-lifetime: 900_000 # 15 минут
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml

logging:
  level:
    org.springframework.transaction: TRACE
    org.springframework.transaction.support: TRACE
    org.springframework.security: TRACE

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health.show-details: always
  health:
    circuit-breakers.enabled: true
    rate limiters.enabled: true

resilience4j:
  rate-limiter:
    metrics:
      enabled: true
    instances:
      rateLimiterApi:
        register-health-indicator: true
        limit-for-period: 1_000_000
        limit-refresh-period: P30D
        timeout-duration: 0s
        allow-health-indicator-to-fail: true
        subscribe-for-events: true
        event-consumer-buffer-size: 50

generation:
  count: 16

external-api:
  base-url: https://api.weatherapi.com
  token: ${WEATHER_API_TOKEN}
  token-param-name: key
  current:
    url: /v1/current.json
    location-param-name: q
    language-param-name: lang
    aqi-param-name: aqi
  bulk-request:
    locations-limit: 49

cache:
  weather:
    size: 64
