INSERT INTO city(id, name)
VALUES (RANDOM_UUID(), 'Moscow'),
       (RANDOM_UUID(), 'Saint Petersburg'),
       (RANDOM_UUID(), 'Novosibirsk'),
       (RANDOM_UUID(), 'Yekaterinburg'),
       (RANDOM_UUID(), 'Kazan'),
       (RANDOM_UUID(), 'Nizhny Novgorod'),
       (RANDOM_UUID(), 'Chelyabinsk'),
       (RANDOM_UUID(), 'Samara'),
       (RANDOM_UUID(), 'Omsk'),
       (RANDOM_UUID(), 'Rostov-on-Don'),
       (RANDOM_UUID(), 'Ufa'),
       (RANDOM_UUID(), 'Krasnoyarsk'),
       (RANDOM_UUID(), 'Voronezh'),
       (RANDOM_UUID(), 'Perm'),
       (RANDOM_UUID(), 'Volgograd'),
       (RANDOM_UUID(), 'Krasnodar'),
       (RANDOM_UUID(), 'Saratov'),
       (RANDOM_UUID(), 'Tyumen'),
       (RANDOM_UUID(), 'Tolyatti'),
       (RANDOM_UUID(), 'Izhevsk'),
       (RANDOM_UUID(), 'Kaliningrad');