INSERT INTO city(id, name)
VALUES (RANDOM_UUID(), 'Москва'),
       (RANDOM_UUID(), 'Санкт-Петербург'),
       (RANDOM_UUID(), 'Новосибирск'),
       (RANDOM_UUID(), 'Екатеринбург'),
       (RANDOM_UUID(), 'Казань'),
       (RANDOM_UUID(), 'Нижний Новгород'),
       (RANDOM_UUID(), 'Челябинск'),
       (RANDOM_UUID(), 'Самара'),
       (RANDOM_UUID(), 'Омск'),
       (RANDOM_UUID(), 'Ростов-на-Дону'),
       (RANDOM_UUID(), 'Уфа'),
       (RANDOM_UUID(), 'Красноярск'),
       (RANDOM_UUID(), 'Воронеж'),
       (RANDOM_UUID(), 'Пермь'),
       (RANDOM_UUID(), 'Волгоград'),
       (RANDOM_UUID(), 'Краснодар'),
       (RANDOM_UUID(), 'Саратов'),
       (RANDOM_UUID(), 'Тюмень'),
       (RANDOM_UUID(), 'Тольятти'),
       (RANDOM_UUID(), 'Ижевск'),
       (RANDOM_UUID(), 'Калининград');