-- Взял отсюда: https://www.weatherapi.com/docs/conditions.json

INSERT INTO weather_type(id, name)
VALUES (RANDOM_UUID(), 'Sunny'),
       (RANDOM_UUID(), 'Clear'),
       (RANDOM_UUID(), 'Partly Cloudy'),
       (RANDOM_UUID(), 'Cloudy'),
       (RANDOM_UUID(), 'Overcast'),
       (RANDOM_UUID(), 'Mist'),
       (RANDOM_UUID(), 'Patchy rain nearby'),
       (RANDOM_UUID(), 'Patchy snow nearby'),
       (RANDOM_UUID(), 'Patchy sleet nearby'),
       (RANDOM_UUID(), 'Patchy freezing drizzle nearby'),
       (RANDOM_UUID(), 'Thundery outbreaks in nearby'),
       (RANDOM_UUID(), 'Blowing snow'),
       (RANDOM_UUID(), 'Blizzard'),
       (RANDOM_UUID(), 'Fog'),
       (RANDOM_UUID(), 'Freezing fog'),
       (RANDOM_UUID(), 'Patchy light drizzle'),
       (RANDOM_UUID(), 'Light drizzle'),
       (RANDOM_UUID(), 'Freezing drizzle'),
       (RANDOM_UUID(), 'Heavy freezing drizzle'),
       (RANDOM_UUID(), 'Patchy light rain'),
       (RANDOM_UUID(), 'Light rain'),
       (RANDOM_UUID(), 'Moderate rain at times'),
       (RANDOM_UUID(), 'Moderate rain'),
       (RANDOM_UUID(), 'Heavy rain at times'),
       (RANDOM_UUID(), 'Heavy rain'),
       (RANDOM_UUID(), 'Light freezing rain'),
       (RANDOM_UUID(), 'Moderate or heavy freezing rain'),
       (RANDOM_UUID(), 'Light sleet'),
       (RANDOM_UUID(), 'Moderate or heavy sleet'),
       (RANDOM_UUID(), 'Patchy light snow'),
       (RANDOM_UUID(), 'Light snow'),
       (RANDOM_UUID(), 'Patchy moderate snow'),
       (RANDOM_UUID(), 'Moderate snow'),
       (RANDOM_UUID(), 'Patchy heavy snow'),
       (RANDOM_UUID(), 'Heavy snow'),
       (RANDOM_UUID(), 'Ice pellets'),
       (RANDOM_UUID(), 'Light rain shower'),
       (RANDOM_UUID(), 'Moderate or heavy rain shower'),
       (RANDOM_UUID(), 'Torrential rain shower'),
       (RANDOM_UUID(), 'Light sleet showers'),
       (RANDOM_UUID(), 'Moderate or heavy sleet showers'),
       (RANDOM_UUID(), 'Light snow showers'),
       (RANDOM_UUID(), 'Moderate or heavy snow showers'),
       (RANDOM_UUID(), 'Light showers of ice pellets'),
       (RANDOM_UUID(), 'Moderate or heavy showers of ice pellets'),
       (RANDOM_UUID(), 'Patchy light rain in area with thunder'),
       (RANDOM_UUID(), 'Moderate or heavy rain in area with thunder'),
       (RANDOM_UUID(), 'Patchy light snow in area with thunder'),
       (RANDOM_UUID(), 'Moderate or heavy snow in area with thunder');